sudo: required
language: python

# which python versions to test
python:
  - "3.5"
  - "3.6"

# Cache directory $HOME/.cache/pip
cache: pip

# command before installation: install all dependencies and run CMAKE config
before_install:
  - python -m pip install --upgrade pip
  - python -m pip uninstall -y sympde
  - python -m pip uninstall -y gelato

# command to install project
install:
  - python -m pip install .

# command to run tests
script:
  - python -m pytest gelato 
